### ISSUE TITLE
New button is not shown on all supported tabs

### ISSUE THREAD

**Issue by glexey** [glexey/CategorySetPluginOutlook2013#2]
New button is not shown in:
1. MESSAGE tab in e-mail read window
2. MEETING tab in Calendar view
3. HOME tab in People view
4. HOME tab in Notes view

**Comment by konsept** [comment]
While categorize is not included by default in the Tags group here it would also be nice to have it in:
5. MESSAGE tab in e-mail send window

**Comment by konsept** [comment]
Looks like you have included this enhancement in v1.2!  Works well, thanks!
